#!/bin/sh
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build  -ldflags="-s -w" -o ./builds/dux-darwin-amd64

CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build  -ldflags="-s -w" -o  ./builds/dux-darwin-arm64

CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build  -ldflags="-s -w"  -o ./builds/dux-win-amd64

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -ldflags="-s -w" -o ./builds/dux-linux-amd64
